### ISSUE TITLE
no top level LICENSE file, suggest MIT

### ISSUE THREAD

**Issue by MarkAtwood** [ros2/choco-packages#13]
There is no top level LICENSE file, and no other license information in this repo.
The MIT license makes the most sense for this repo.

**Comment by mjcarroll** [comment]
In this case, the actual packaging information is licensed under Apache 2.0, but an additional NOTICE file is required, because the source and generated artifacts of each package are governed by their own respective (included) licenses:

* asio: https://github.com/ros2/choco-packages/blob/latest/package/asio/tools/LICENSE.txt
* eigen: https://github.com/ros2/choco-packages/blob/latest/package/eigen/tools/LICENSE.txt
* log4cxx: https://github.com/ros2/choco-packages/blob/latest/package/log4cxx/tools/LICENSE.txt
* opensplice: https://github.com/ros2/choco-packages/blob/latest/package/opensplice/legal/LICENSE.txt
* openssl: https://github.com/ros2/choco-packages/blob/latest/package/openssl/legal/LICENSE.txt
* qt-sdk: https://github.com/ros2/choco-packages/blob/latest/package/qt-sdk/legal/LICENSE.txt
* rti-connext: https://github.com/ros2/choco-packages/blob/latest/package/rti-connext/legal/RTI_OpenCommunitySourceLicense_4032_Rev06-16.pdf
* tinyxml-usestl: https://github.com/ros2/choco-packages/blob/latest/package/tinyxml-usestl/tools/tools/LICENSE.txt
* tinyxml2: https://github.com/ros2/choco-packages/blob/latest/package/tinyxml2/tools/LICENSE.txt

If you could create a PR to capture this, I'd be happy to get it in.

**Comment by mm318** [comment]
The PR https://github.com/ros2/choco-packages/pull/14 has been created to capture this.

**Comment by nuclearsandwich** [comment]
Resolved by #14. Thanks @mm318!
