### ISSUE TITLE
Issue with `$PSScriptRoot` on Windows 7

### ISSUE THREAD

**Issue by vfdev-5** [ros2/choco-packages#2]
Hi,

I'm trying to install ROS2 dependencies as choco packages from this repository (following [this](https://github.com/ros2/ros2/wiki/Windows-Install-Binary#install-dependencies)). 
I successfully installed `choco` and `python3`. When I install these dependencies or just one of these, I get the following error:
```
> C:\Users\USER\Downloads>choco install -y -s C:\Users\USER\Downloads\ asio
Chocolatey v0.10.5
Installing the following packages:
asio
By installing you accept licenses for the packages.

asio v1.10.6
asio package files install completed. Performing other installation steps.
ERROR: The term '\regKeys.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
The install of asio was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\asio\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - asio (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\asio\tools\chocolateyinstall.ps1'.
 See log for details.
```
Somehow, powershell variable `$RSScriptRoot` is empty when `asio\tools\chocolateyinstall.ps1` is executed. 
Can you please hint me where is the problem ?

Thanks

**Comment by nuclearsandwich** [comment]
@vfdev-5,

Can you please provide the following information so we can try and troubleshoot:

- your Windows OS version
- the output of the Powershell command `echo $PSVersionTable`
- the referenced chocolatey.log file as a GitHub [gist](https://gist.github.com)

I just tested installing the asio package in a clean installation of Windows 10 with Chocolatey 0.10.5, which is the current version of Chocolatey and the one you're using as well.

**Comment by vfdev-5** [comment]
Hi, @nuclearsandwich, thanks for quick answer. Here is the information you ask:
- Chocolatey v0.10.5
- Windows 7
- `echo $PSVersionTable`
```
Name                           Value
----                           -----
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```
- Log file [chocolatey.log.txt](https://github.com/ros2/choco-packages/files/992283/chocolatey.log.txt) 

Cheers

**Comment by dirk-thomas** [comment]
ROS 2 only aims to support Windows 8.1 and higher at the moment. In the near future we will only test and support Windows 10 (see https://github.com/ros2/ros2/wiki/Windows-Development-Setup#prerequisites / https://github.com/ros2/ros2/wiki/Windows-Install-Binary#system-requirements). So it could be that this problem is specific to Windows 7. If you can reproduce the problem on a newer Windows version we are happy to look into it.

**Comment by lixiaobai09** [comment]
I have also this problem for windows 7. The reason which cause this problem is that variable $PSScriptRoot not defined in windows 7.  I have solved this problem with following steps:
First, choco install without option -y.
Second, the shell window will ask you choose yes or no. At this time, modified the chocolateyinstall.ps1 in directory. Seting the PSScriptRoot as 'C:\ProgramData\chocolatey\lib\asio\tools' before run regKeys.ps1.
Finally, enter the 'yes' at shell window.
Wish this answer can help somebody!
